
language: android
jdk: oraclejdk8
sudo: false

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - QEMU_AUDIO_DRV=none

before_install:
- yes | sdkmanager "platforms;android-27"

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository

  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+


script:
- ./gradlew build jacocoTestReportDebug

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.android
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/