language: android

jdk:
  - oraclejdk8

install:
  - echo yes | sdkmanager "tools" &>/dev/null
  - echo yes | sdkmanager "platform-tools" &>/dev/null
  - echo yes | sdkmanager "build-tools;27.0.2" &>/dev/null
  - echo yes | sdkmanager "platforms;android-27" &>/dev/null


android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27

script:
   - ./gradlew build connectedCheck
