name: CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: set up JDK 19
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: '19'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.5

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.3

      - name: Lint
        run: ./gradlew detekt

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew jacocoTestReportDebug

      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODE_COV_TOKEN  }}
