name: CI
on: [ push ]
jobs:
  Validate-Gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ./.github/actions/setup
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.5
  Build:
    runs-on: ubuntu-latest
    needs: [ Validate-Gradle ]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ./.github/actions/setup
      - name: Build Debug APK
        run: ./gradlew assembleDebug
  Lint:
    runs-on: ubuntu-latest
    needs: [ Build ]
    strategy:
      matrix:
        command: [ detekt, lint, ktfmtCheck, sortDependencies --mode check ]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ./.github/actions/setup
      - name: Lint
        run: ./gradlew ${{ matrix.command }}
  Tests:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ./.github/actions/setup
      - name: Run Unit Tests
        run: ./gradlew jacocoTestReportDebug
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODE_COV_TOKEN  }}
