name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3

#      - name: Lint TODO add back detekt
#        uses: eskatos/gradle-command-action@v1
#        with:
#          arguments: detekt

      - name: Build Debug APK
        run: ./gradlew assembleDebug

#      - name: Run Unit Tests TODO add back JaCoCo plugin
#        uses: eskatos/gradle-command-action@v1
#        with:
#          arguments: jacocoTestReportDebug

      - name: Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          token: ${{ secrets.CODE_COV_TOKEN  }}
