name: CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - name: set up JDK 11
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt

      - name: Build Debug APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug

      - name: Run Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jacocoTestReportDebug

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODE_COV_TOKEN  }}
