name: CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: set up JDK 11
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Lint
        uses: eskatos/gradle-command-action@v2
        with:
          arguments: detektAll

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        uses: eskatos/gradle-command-action@v2
        with:
          arguments: jacocoTestReportDebug

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODE_COV_TOKEN  }}
