name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.18
        with:
          repo-token: ${{ secrets.GRADLE_UPGRADE_TOKEN }}
          set-distribution-checksum: false
